name: Docker Manage the v8 Jobs and related Coders.

on: workflow_dispatch

jobs:
  docker-build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: build-v8-sysroot-bullseye-x86_64
      run: |                              
        # Note that this is exactly what docker build does for each RUN defined layer
        cat <<'EOF' | docker run -i --name container_build-v8-sysroot-bullseye-x86_64 debian:bullseye-slim
         apt update && apt upgrade -y && apt install -y git curl python lsb-release sudo
         mkdir build && cd build
         git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
         /build/depot_tools/gclient
         /build/depot_tools/fetch v8 
         cd /build/v8 
         git checkout branch-heads/10.8 
         /build/depot_tools/gclient sync
         /build/v8/build/install-build-deps.sh --no-syms --no-chromeos-fonts --no-arm --no-nacl --no-backwards-compatible
         /build/v8/tools/dev/v8gen.py x64.release -- target_os=\"linux\" target_cpu=\"x64\" v8_target_cpu=\"x64\" \
          v8_use_external_startup_data=false \
            v8_enable_future=true \
            is_official_build=false \
            is_component_build=false \
            is_cfi=false \
            is_asan=false \
            is_clang=false \
            use_custom_libcxx=false \
            use_custom_libcxx_for_host=false \
            use_sysroot=false \
            use_gold=false \
            is_debug=false \
            treat_warnings_as_errors=false \
            v8_enable_i18n_support=false \
            symbol_level=0 \
            v8_static_library=true \
            v8_monolithic=true \
            proprietary_codecs=false \
            toolkit_views=false \
            use_aura=false \
            use_dbus=false \
            use_gio=false \
            use_glib=false \
            use_ozone=false \
            use_udev=false \
            clang_use_chrome_plugins=false \
            v8_deprecation_warnings=false \
            v8_enable_gdbjit=false \
            v8_imminent_deprecation_warnings=false \
            v8_enable_pointer_compression=true \
            v8_scriptormodule_legacy_lifetime=true \
            v8_enable_sandbox=false
        EOF

        ## Build Cache the updated image
        docker commit container_build-v8-sysroot-bullseye-x86_64 image_v8-sysroot-bullseye-x86_64:latest 
        mkdir build-deps
        docker save image_v8-sysroot-bullseye-x86_64:latest | gzip > build-deps/image_v8-sysroot-bullseye-x86_64_latest.tar.gz
    - uses: actions/upload-artifact@v3
      with:
        name: v8-sysroot-bullseye-x86_64
        path: build-deps
        if-no-files-found: error

