name: Docker Manage the v8 Jobs and related Coders.

on: workflow_dispatch

jobs:
  docker-build:
    runs-on: ubuntu-20.10
    steps:
    - uses: actions/checkout@v3
    - name: Open the Office for the Ninjas makes coders feel less cheap to be called Ninja implicits hornor.
      id: set-env
      run: |
        echo "DATE=$(date -I)" >> $GITHUB_ENV
        export WORKDIR="$(pwd)/build"
        echo "WORKDIR=${WORKDIR}" >> $GITHUB_ENV
        echo "V8=${WORKDIR}/v8" >> $GITHUB_ENV
        export DEPOT_TOOLS="${WORKDIR}/depot_tools"
        echo "DEPOT_TOOLS=${DEPOT_TOOLS}" >> $GITHUB_ENV
        echo "PATH=${DEPOT_TOOLS}:$PATH" >> $GITHUB_ENV
        echo "BRANCH=branch-heads/10.7" >> $GITHUB_ENV
    - name: build-linux-x86_64 - Turning on the Servers for the Ninja Coders that work on this job.
      id: cache
      uses: actions/cache@v3
      with:
        path: build
        key: ${{ runner.os }}-x86_64
    - name: build-linux-x86_64 - Create work for Ninja's
      if: steps.cache.outputs.cache-hit != 'true'
      env:
        PATH: ${{ env.PATH }}
        DEPOT_TOOLS: ${{ env.DEPOT_TOOLS }}
      run: |
        export DOCKER_BUILD=$(docker build .)
        echo "DOCKER_BUILD=$DOCKER_BUILD" >> $GITHUB_ENV
        mkdir build
        docker save $DOCKER_BUILD | gzip > build/myimage_latest.tar.gz

