name: v8 github linux x64 CI

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Get Current ENV
      id: set-env
      run: |
        echo "DATE=$(date -I)" >> $GITHUB_ENV
        echo "CWD=$(pwd)/build" >> $GITHUB_ENV
        echo "V8=$(pwd)/build/v8" >> $GITHUB_ENV
        echo "DEPOT_TOOLS=$(pwd)/build/depot_tools" >> $GITHUB_ENV
        echo "PATH=$(pwd)/build/depot_tools:$PATH" >> $GITHUB_ENV
        echo "T=$DEPOT_TOOLS" >> $GITHUB_ENV
    - name: Cache Build Deps
      id: cache-build-deps
      uses: actions/cache@v3
      with:
        path: build
        key: ${{ runner.os }}-build-deps-${{ env.DATE }}
    - name: Install dependencies
      if: steps.cache-build-deps.outputs.cache-hit != 'true'
      env:
        PATH: ${{ env.PATH }}
        DEPOT_TOOLS: ${{ env.DEPOT_TOOLS }}
      run: |
        mkdir -p build && cd build
        sudo apt-get update -y && sudo apt-get upgrade -y && sudo apt-get install -y git curl python lsb-release
        git clone --single-branch https://chromium.googlesource.com/chromium/tools/depot_tools.git
        export PATH="$DEPOT_TOOLS:${PATH}"
        gclient
        fetch v8
        cd v8 && git checkout branch-heads/10.7
    - name: Configure
      env: 
        BRANCH: branch-heads/10.7
        PATH: ${{ env.PATH }}
        V8: ${{ env.V8 }}
        DEPOT_TOOLS: ${{ env.DEPOT_TOOLS }}
      run: |
        cd $V8 && git checkout $BRANCH
        $DEPOT_TOOLS/gclient sync
        $V8/build/install-build-deps.sh --no-syms --no-chromeos-fonts --no-arm --no-nacl --no-backwards-compatible
        $V8/tools/dev/v8gen.py x64.release -- target_os=\"linux\" target_cpu=\"x64\" v8_target_cpu=\"x64\" \
        v8_use_external_startup_data=false \
        v8_enable_future=true \
        is_official_build=false \
        is_component_build=false \
        is_cfi=false \
        is_asan=false \
        is_clang=false \
        use_custom_libcxx=false \
        use_custom_libcxx_for_host=false \
        use_sysroot=false \
        use_gold=false \
        is_debug=false \
        treat_warnings_as_errors=false \
        v8_enable_i18n_support=false \
        symbol_level=0 \
        v8_static_library=true \
        v8_monolithic=true \
        proprietary_codecs=false \
        toolkit_views=false \
        use_aura=false \
        use_dbus=false \
        use_gio=false \
        use_glib=false \
        use_ozone=false \
        use_udev=false \
        clang_use_chrome_plugins=false \
        v8_deprecation_warnings=false \
        v8_enable_gdbjit=false \
        v8_imminent_deprecation_warnings=false \
        v8_enable_pointer_compression=true \
        v8_scriptormodule_legacy_lifetime=true \
        v8_enable_sandbox=false
#    - name: Cache Build Result
#      id: cache-build
#      uses: actions/cache@v3
#      with:
#        path: build
#        key: ${{ runner.os }}-build-${{ env.current_date }}
#    - name: Build
#      if: steps.cache-build.outputs.cache-hit != 'true'
#      run: ninja v8_monolith -C out.gn/x64.release/ -j $(getconf _NPROCESSORS_ONLN)
#    - name: Run distcheck
#      run: ls


