name: v8 github linux x64 CI

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Get Current ENV
      id: date
      run: |
        echo "current_date=$(date -I)" >> $GITHUB_ENV
        echo "current_path=$(date -I)" >> $GITHUB_ENV
        echo "current_build_dir=$(pwd)" >> $GITHUB_ENV
        echo "current_build_pwd=$PWD" >> $GITHUB_ENV
    - name: Cache Build Deps
      id: cache-build-deps
      uses: actions/cache@v3
      with:
        path: build
        key: ${{ runner.os }}-build-deps-${{ env.current_date }}
    - name: Install dependencies
      if: steps.cache-build-deps.outputs.cache-hit != 'true'
      run: |
        mkdir -p build && cd build
        sudo apt-get update -y && sudo apt-get upgrade -y && sudo apt-get install -y git curl python lsb-release
        rm -rf depot_tools
        git clone --single-branch https://chromium.googlesource.com/chromium/tools/depot_tools.git
        export PATH="$PWD/depot_tools:${PATH}"
        gclient
        fetch v8
        cd v8
        git checkout branch-heads/10.7

