name: Manage the v8 Jobs and related Coders.

on: workflow_dispatch

jobs:
  build-ubuntu-22_04-x86_64:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Open the Office for the Ninjas makes coders feel less cheap to be called Ninja implicits hornor.
      id: set-env
      run: |
        echo "DATE=$(date -I)" >> $GITHUB_ENV
        export WORKDIR="$(pwd)/build"
        echo "WORKDIR=${WORKDIR}" >> $GITHUB_ENV
        echo "V8=${WORKDIR}/v8" >> $GITHUB_ENV
        export DEPOT_TOOLS="${WORKDIR}/depot_tools"
        echo "DEPOT_TOOLS=${DEPOT_TOOLS}" >> $GITHUB_ENV
        echo "PATH=${DEPOT_TOOLS}:$PATH" >> $GITHUB_ENV
        echo "BRANCH=branch-heads/10.7" >> $GITHUB_ENV
    - name: build-linux-x86_64 - Turning on the Servers for the Ninja Coders that work on this job.
      id: cache-build-deps
      uses: actions/cache@v3
      with:
        path: build
        key: ${{ runner.os }}-build-deps-${{ env.DATE }}
    - name: build-linux-x86_64 - Create work for Ninja's
      if: steps.cache-build-deps.outputs.cache-hit != 'true'
      env:
        PATH: ${{ env.PATH }}
        DEPOT_TOOLS: ${{ env.DEPOT_TOOLS }}
      run: |
        mkdir -p build && cd build
        sudo apt-get update -y && sudo apt-get upgrade -y && sudo apt-get install -y git curl lsb-release python-is-python3 build-essentials
        git clone --single-branch https://chromium.googlesource.com/chromium/tools/depot_tools.git
        $DEPOT_TOOLS/gclient
        $DEPOT_TOOLS/fetch v8
    - name: build-linux-x86_64 - Send Recruiter a Request to find a Code Ninjas that know how to Code and Build Software for linux-x86_64
      if: steps.cache-build-deps.outputs.cache-hit != 'true'
      env: 
        BRANCH: ${{ env.BRANCH }}
        PATH: ${{ env.PATH }}
        V8: ${{ env.V8 }}
        DEPOT_TOOLS: ${{ env.DEPOT_TOOLS }}
      run: |
        cd $V8 && git checkout $BRANCH
        $DEPOT_TOOLS/gclient sync
        $V8/build/install-build-deps.sh --no-syms --no-chromeos-fonts --no-arm --no-nacl --no-backwards-compatible
        $V8/tools/dev/v8gen.py x64.release -- target_os=\"linux\" target_cpu=\"x64\" v8_target_cpu=\"x64\" \
        v8_use_external_startup_data=false \
        v8_enable_future=true \
        is_official_build=false \
        is_component_build=false \
        is_cfi=false \
        is_asan=false \
        is_clang=false \
        use_custom_libcxx=false \
        use_custom_libcxx_for_host=false \
        use_sysroot=false \
        use_gold=false \
        is_debug=false \
        treat_warnings_as_errors=false \
        v8_enable_i18n_support=false \
        symbol_level=0 \
        v8_static_library=true \
        v8_monolithic=true \
        proprietary_codecs=false \
        toolkit_views=false \
        use_aura=false \
        use_dbus=false \
        use_gio=false \
        use_glib=false \
        use_ozone=false \
        use_udev=false \
        clang_use_chrome_plugins=false \
        v8_deprecation_warnings=false \
        v8_enable_gdbjit=false \
        v8_imminent_deprecation_warnings=false \
        v8_enable_pointer_compression=true \
        v8_scriptormodule_legacy_lifetime=true \
        v8_enable_sandbox=false
    - name: build-linux-x86_64 - Hire Ninja Coders but prepare Papers for fireing them fast after they finished the job.
      id: cache-build
      uses: actions/cache@v3
      with:
        path: build
        key: ${{ runner.os }}-build-${{ env.DATE }}
    - name: build-linux-x86_64 - Ninjas Coding on - build-linux-x86_64
      if: steps.cache-build.outputs.cache-hit != 'true'
      env: 
        PATH: ${{ env.PATH }}
        V8: ${{ env.V8 }}
      run: cd $V8 && ninja v8_monolith -C out.gn/x64.release/ -j $(getconf _NPROCESSORS_ONLN)
    - name: build-linux-x86_64 - Ninjas finished the job coders can get Fired and rehired later more cheap from the cache.
      run: ls


